# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib aqlyzer, .registration = TRUE
NULL

#' Find the linear range of a fluorescence curve by maximising
#' window R² over all valid start/end index pairs.
#'
#' @param rfu  Numeric vector of RFU values (time-ordered).
#' @param minPoints  Minimum number of points a window must span.
#' @return Integer vector of length 2: c(start, end), 1-based.
#' @export
findLinearRangeRust <- function(rfu, minPoints) .Call(wrap__findLinearRangeRust, rfu, minPoints)

# nolint end
