# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib aqlyzer, .registration = TRUE
NULL

#' Find the linear range of a fluorescence curve by maximising
#' window R² over all valid start/end index pairs.
#'
#' @param rfu  Numeric vector of RFU values (time-ordered).
#' @param min_points  Minimum number of points a window must span.
#' @return Integer vector of length 2: c(start_idx, end_idx), 1-based.
#' @export
find_linear_range_rust <- function(rfu, min_points) .Call(wrap__find_linear_range_rust, rfu, min_points)

# nolint end
